Added Packages, Controllers are done.
Ismail-butt/HouseTable pull request #1
Opened 2022-10-10 15:56 UTC by mIsmail-dev

### Remaining Tasks

- Config File
- Error Handler
- Deployment + MongoDB Atlas

2022-10-11 16:26 UTC, bilalashraf1710 commented on controllers/patientController.js
> +  if (error) {
We can improve it, like em seeing the same code in each endpoint so may be a function that validates the body

2022-10-11 16:26 UTC, bilalashraf1710 commented on controllers/patientController.js
> +  const patients = await Patient.find().populate("appointments", "fee isPaid");
Fee isPaid is an enum? if yes then just use paid/unpaid

2022-10-11 16:26 UTC, bilalashraf1710 commented on controllers/patientController.js
> +  result.popularPet = patients.reduce((acc, patient) => {
Can be divide into function so if we need popular pet in some other function then we can just call to that function

2022-10-11 16:26 UTC, bilalashraf1710 commented on controllers/patientController.js
> +module.exports.createPatient = createPatient;
module.exports = {
createPatien: cretaPatient,
getPatient... 
}???
POSSIBLE?

2022-10-11 16:26 UTC, bilalashraf1710 commented on index.js
> +const dotenv = require("dotenv").config()
yup we should have an idea about dotenv.. but can we use .env ???

2022-10-12 07:21 UTC, mIsmail-dev commented on index.js
> +const dotenv = require("dotenv").config()
yes, we can use it. Basically, I have created a .env file in the project. This .env file push environment variables to the process. Then, to use that .env file, we use dotenv package. This package loads environment variables from a . env file into the running process.

2022-10-12 07:23 UTC, mIsmail-dev commented on controllers/patientController.js
> +module.exports.createPatient = createPatient;
yes, It is possible. **I have used this method before** But in the mosh course, mosh exported the functions by this method. So, I followed mosh method in this Project.

2022-10-12 07:35 UTC, mIsmail-dev commented on controllers/patientController.js
> +  result.popularPet = patients.reduce((acc, patient) => {
yep, I will make this function, and also I will try to divide any other functions if I thought They should be divided.

2022-10-12 07:40 UTC, mIsmail-dev commented on controllers/patientController.js
> +  const patients = await Patient.find().populate("appointments", "fee isPaid");
it's not an enum. It's a boolean. By default, isPaid is false meaning the Patient has not paid the fee. we will change isPaid to true when the Patient will pay the fee. Also, I am using a currency field which is an enum like USD, Eur, and Bitcoin.

2022-10-12 08:37 UTC, mIsmail-dev commented on controllers/patientController.js
> +  if (error) {
I already have a function name **validate** which validates the body. I have made this function in the model file.

2022-10-12 10:16 UTC, Shazil2154 requested changes

2022-10-12 10:16 UTC, Shazil2154 commented on controllers/patientController.js
> +    throw new Error("The patient with given ID was not found");
`The patient with Id ${req.params.id} was not found`

2022-10-12 10:16 UTC, Shazil2154 commented on controllers/patientController.js
> +  const newPatient = new Patient({
const {name, type, ownerName, ownerAddress, ownerPhoneNo} = req.body;

2022-10-12 10:16 UTC, Shazil2154 commented on controllers/patientController.js
> -    const {error} = validate(req.body)
you can create a middleware for validation

2022-10-12 10:16 UTC, Shazil2154 commented on controllers/patientController.js
> +    req.params.id,
same as above

2022-10-12 10:16 UTC, Shazil2154 commented on index.js
> +    app.use(morgan('dev'))
if we are implementing morgan we should use it for production as well

2022-10-12 10:16 UTC, Shazil2154 commented on index.js
> +// Builtin Middlewares
these are custom middlewares IMO

2022-10-12 10:16 UTC, Shazil2154 commented on package.json
>      "mongoose": "^6.6.4",
nodemon should be a dev dependency

2022-10-12 10:16 UTC, Shazil2154 commented on utils/utils.js
> +// will return most Popular pet
function names explains its purpose. no need for the comments

2022-10-12 10:16 UTC, Shazil2154 commented on utils/utils.js
> +          if (appointment.isPaid) {
you can create a function to perform both actions

2022-10-12 10:35 UTC, mIsmail-dev commented on controllers/patientController.js
> +    throw new Error("The patient with given ID was not found");
done

2022-10-12 11:09 UTC, mIsmail-dev commented on utils/utils.js
> +          if (appointment.isPaid) {
done

2023-12-31 16:12 UTC, merged